services:
  - type: web
    name: whale-radar-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python whale_bot_ai.py"
    branch: main
    autoDeploy: true
